export const metadata = {
	title: "S V Scientific | Products",
	description: "Generated by create next app",
};

export default function Layout({ children }) {
	return (
		<>
			{children}
		</>
	);
}
